#!/usr/bin/env bash
# PLM calibration coefficients — sunnycove, calibrated from N=8
# Generated by: mx2/tools/mcpat_plm_fit.py
#
# Model:  P_nocache(f) = b_f + a_util * U_sum + a_ipc * U_sum * ipc
#   U_sum        = Σ per-core util fractions  (= avg_util * N_cores)
#   ipc          = total_ins / (N_cores * total_cycles)
#   U_sum * ipc  = interaction term (busy-core compute intensity)
#
# Portability: U_sum and U_sum*ipc both scale with N_cores,
# so coefficients fitted from N=8 should apply at other N.
# Validate with --validate-csv before deploying at a different N.
#
# Calibration: 475 runs, 17 frequencies, uarch=sunnycove
PLM_N=17
PLM_F=(      2.000   2.200   2.400   2.600   2.660   2.700   2.800   2.820   2.840   2.900   3.000   3.100   3.200   3.300   3.400   3.500   3.600  )
PLM_B=(     -287.1557  -659.6160  -401.3148  -375.6779  488.1072  208.6728  284.6903   89.4324  -2239974.9564  -230.5169  -1029.5886  -159.0329   53.5199  -256.1214  406.7066   80.8254  487.0330  )
PLM_AUTIL=( 309.7248  682.5260  424.3214  398.5554  -465.2623  -185.8172  -261.6528  -68.3917  2239963.2875  253.4823  1053.0635  182.0481  -30.5617  279.4464  -383.6786  -57.7995  -463.9503  )
PLM_AIPC=(   10.0542   11.6874   12.3615   14.8066   12.9578   14.3163   14.3504   22.2252  6480.6616   16.9288   18.2100   18.5306   19.0683   19.5614   19.2869   21.5862   20.3568  )
