2:
  rd_cyc: 3
  wr_cyc: 165
  r_pj: 156
  w_pj: 156
  leak_mw: 13.617

16:
  rd_cyc: 6
  wr_cyc: 171
  r_pj: 312
  w_pj: 307
  leak_mw: 101.6

32:
  rd_cyc: 9
  wr_cyc: 174
  r_pj: 389
  w_pj: 384
  leak_mw: 94.476

128:
  rd_cyc: 26
  wr_cyc: 201
  r_pj: 685
  w_pj: 667
  leak_mw: 185.785
